#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/ldform.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cp --no-header src/ldform.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "done."

